Documentation:
  Enabled: false
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - config/initializers/backtrace_silencers.rb
    - config/application.rb
    - Gemfile