# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54d0b2ff6deb7f47c653ce917acd6786c55710fd75eb22528c9e783e8dd90ce64a75087756af24d910a37190595a37d0476ad02b5a41978a4d34c5c0374ebda0

test:
  secret_key_base: 718331c0ae17064ea485aa36b23536e1885053f20ed460a6efcd291624e672b3d97664efdae03684017058ea1985f0706fac8d806f1e7352b4bcd91e6c50dfa0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_secret: <%= ENV["GOOGLE_SECRET"] %>
